# Generated by Django 3.2.3 on 2021-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('ph_no', models.IntegerField(null=True, verbose_name='Phn_no')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
